# Use an official ubuntu runtime as a parent image
FROM ubuntu:16.04

# Set the working directory to /app
WORKDIR /app

# Copy the app directory contents into the container at /app
ADD /app /app

# Install dependencies
RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y build-essential cmake git pkg-config \
    && apt-get install -y libprotobuf-dev libleveldb-dev libsnappy-dev libhdf5-serial-dev protobuf-compiler \
    && apt-get install -y libatlas-base-dev \
    && apt-get install -y --no-install-recommends libboost-all-dev \
    && apt-get install -y libgflags-dev libgoogle-glog-dev liblmdb-dev \
    && apt-get install -y python-pip \
    && apt-get install -y python-dev \
    && apt-get install -y python-numpy python-scipy \
    && apt-get install -y libopencv-dev \
    && rm -rf /var/lib/apt/lists/*

# Install some python packages
#RUN pip install --no-cache-dir --upgrade pip setuptools wheel
#RUN pip install --no-cache-dir future hypothesis numpy protobuf six

# Caffe installation: Jonlong's special version for CascadeFCN
RUN git clone --depth 1 --branch jonlong --recursive https://github.com/mohamed-ezz/caffe.git \
    && cd caffe \
    && cp Makefile.config.example Makefile.config \
    && sed -i 's|# CPU_ONLY := 1|CPU_ONLY := 1|' Makefile.config \
    && sed -i 's|/usr/lib/python2.7/dist-packages/numpy/core/include|/usr/local/lib/python2.7/dist-packages/numpy/core/include|' Makefile.config \
    && sed -i 's|# WITH_PYTHON_LAYER := 1|WITH_PYTHON_LAYER := 1|' Makefile.config \
    && sed -i 's|INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include|INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial|' Makefile.config \
    && sed -i 's|LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib|LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/hdf5/serial|' Makefile.config \
    && cd python \
    && pip install jupyter==1.0.0 \
    && pip install -r requirements.txt \
    && pip install matplotlib \
    && pip install dicom==0.9.9.post1 \
    && pip install natsort==5.3.2 \
    && cd .. \
    && make all -j $(($(nproc) + 1)) \
    && make test -j $(($(nproc) + 1)) \
    && make runtest -j $(($(nproc) + 1)) \
    && make pycaffe -j $(($(nproc) + 1)) \
    && make distribute -j $(($(nproc) + 1))

ENV PYTHONPATH=/app/caffe/python:$PYTHONPATH
